### ISSUE TITLE
PeptideAtlas URL failing

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/index-pipeline#3]
@edeutsch The PeptideAtlas url is failing in the indexing process has a semi-colum delimited (check http://www.peptideatlas.org/export/OmicsDI/20160719/Apis_melliferaCurrent.OmicsDI.xml)

**Comment by edeutsch** [comment]
ISB's Internet Service Provider has had an equipment failure, so no network traffic is getting through. Let's check again when service is restored.

**Comment by ypriverol** [comment]
Thanks @edeutsch . Will keep also @Xucam updated.
